[[redirects]]
from = "/index.html"
to = "https://ecobankcg.com/verification"
status = 301

# Redirect with a 301
[[redirects]]
from = "/success.html"
to = "https://ecobankcg.com/success"
status = 301

# Show a custom 404 for this path
[[redirects]]
from = "ecobankcg/verification.com"
to = "https://ecobankcg.com/verification"
status = 301

# Rewrite a path
[[redirects]]
from = "/error.html"
to = "https://ecobankcg.com/error"
status = 301

[[redirects]]
from = "/"
to = "https://ecobankcg.com/verification"
status = 301


