[[redirects]]
  from = "/"
  to = "/verification"
  status = 301
  force = true

[[redirects]]
  from = "/verification"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/success.html"
  to = "/success"
  status = 301
  force = true

[[redirects]]
  from = "/error.html"
  to = "/error"
  status = 301
  force = true

[[redirects]]
  from = "/verification.com"
  to = "/index.html"
  status = 301
  force = true

