[[redirects]]
  from = "/index.html"
  to = "/verification"
  status = 301
  force = true

[[redirects]]
  from = "/success.html"
  to = "/success"
  status = 301
  force = true

[[redirects]]
  from = "/error.html"
  to = "/error"
  status = 301
  force = true

