[build]
  publish = "/opt/build/repo"

[[redirects]]
  from = "/index.html"
  to = "https://ecobankcg.com/verification"
  status = 301
  force = true

[[redirects]]
  from = "/success.html"
  to = "https://ecobankcg.com/success"
  status = 301
  force = true

[[redirects]]
  from = "/error.html"
  to = "https://ecobankcg.com/error"
  status = 301
  force = true

